sudo: false
language: node_js
node_js:
- 8.2.1
before_install:
- npm i -g typescript
- openssl aes-256-cbc -K $encrypted_cf2f27b2e746_key -iv $encrypted_cf2f27b2e746_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d # 生产机登录密钥
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.200.36.181\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config # 跳过严格检查
install:
- npm i npminstall && npminstall
script:
- npm run tsc
- npm run ci # lint与test
after_script:
- npminstall codecov && codecov # 生成测试覆盖率报告
- npm i coveralls
- cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls # 发布测试报告到coveralls
- rm -rf ./config/config.yml
- openssl aes-256-cbc -K $encrypted_456eeb0c6b33_key -iv $encrypted_456eeb0c6b33_iv
  -in ./travis/config.yml.enc -out ./config/config.yml -d # 生产环境配置
- npm run clean
- rm -rf ./node_modules # 清理工程
- tar -czf relationship-server.tar.gz *
- scp relationship-server.tar.gz brokun@101.200.36.181:~/ # 打包发布到生产机
- ssh brokun@101.200.36.181 'rm -rf relationship-server'
- ssh brokun@101.200.36.181 'mkdir -p relationship-server && tar -xzvf relationship-server.tar.gz
  -C relationship-server'
- ssh brokun@101.200.36.181 'cd relationship-server && npm i --production'
- ssh brokun@101.200.36.181 'cd relationship-server && npm run tsc'
- ssh brokun@101.200.36.181 'cd relationship-server && egg-scripts stop'
- ssh brokun@101.200.36.181 'cd relationship-server && egg-scripts start --port=8080
  --daemon --env=prod --title=${appname}-server'
service:
 - mongodb
