sudo: false
language: node_js
node_js:
- 8.2.1
before_install:
- npm i -g typescript
- openssl aes-256-cbc -K $encrypted_cf2f27b2e746_key -iv $encrypted_cf2f27b2e746_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.200.36.181\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm i npminstall && npminstall
script:
- npm run tsc
- npm run ci
after_script:
- npminstall codecov && codecov
- cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls
- npm run clean
- rm -rf node_modules
- tar -czf relationship-server.tar.gz *
- scp relationship-server.tar.gz brokun@101.200.36.181:~/
- ssh brokun@101.200.36.181 'rm -rf relationship-server'
- ssh brokun@101.200.36.181 'mkdir -p relationship-server && tar -xzvf relationship-server.tar.gz
  -C relationship-server'
- ssh brokun@101.200.36.181 'cp config.default.ts relationship-server/config/config.default.ts'
- ssh brokun@101.200.36.181 'cd relationship-server && npm i --production'
- ssh brokun@101.200.36.181 'cd relationship-server && npm run tsc'
- ssh brokun@101.200.36.181 'cd relationship-server && egg-scripts stop'
- ssh brokun@101.200.36.181 'cd relationship-server && egg-scripts start --port=8080
  --daemon --env=prod --title=${appname}-server'
notifications:
  slack:
    secure: $slack_secure

