sudo: false
language: node_js
node_js:
- '7.10.1'

before_install:
- openssl aes-256-cbc -K $encrypted_cf2f27b2e746_key -iv $encrypted_cf2f27b2e746_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d

install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
