sudo: false
language: node_js
node_js:
- '7.10.1'

before_install:
- openssl aes-256-cbc -K $encrypted_cf2f27b2e746_key -iv $encrypted_cf2f27b2e746_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.200.36.181\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- tar -czf relationship-server.tar.gz *
install:
- npm i npminstall && npminstall
script:
- npm run ci
after_script:
- npminstall codecov && codecov
- npm i coveralls
- cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls
- scp relationship-server.tar.gz brokun@101.200.36.181:~/
- ssh brokun@101.200.36.181 'rm -rf relationship-server'
- ssh brokun@101.200.36.181 'mkdir -p relationship-server && tar -xzvf relationship-server.tar.gz -C blogSource'
- ssh brokun@101.200.36.181 '. ./relationship-server.sh'
